# -*- coding: utf-8 -*-
"""código_Salary_Predição

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAgtuw8KguPK8e6HD0mEyL2nNomFFicA

* PREPARAÇÃO DE DADOS
- Coleta
- Enriquecimento
* LIMPEZA, TRANSFORMAÇÃO E REDUÇÃO
- Limpeza de informações ausentes
- Limpeza de inconsistência
- Limpeza de valores não pertencente ao domínio 
- Limpeza de valores redundantes
- Discretização 
- Normalização
- Calibração
- (Codificação de dados categóricos) 
- (Redução de dados)
* ANÁLISE EXPLORATÓRIA
- Sumário de 5 números
- Exinição de caule e folhas
- exibição de scatterplot matrix
- exibição por outliers
- residual plot
- bag plot
- smoother
- robust variante
- reexpression
- median polish
-- nas vizualizações de dados --
+ Graficos para valores numéricos e categóricos
+ Medidas de dispersão
+ Graáficos de pares seaborn

## PREPARAÇÃO DE DADOS

Coleta de dados
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Vamos olhar o dataframe para ter algumas informações

"""
Estas são as variáveis deste conjunto de dados
Age                 > apresentando a idade de cada uma das ocorrências                  
Gender              > Informa o gênero 
Education Level     > o Nível de educação das ocorrências 
Job Title           > Os títulos dos cargos de trabalho ocupados  
Years of Experience > Anos de experiência trabalhados  
Salary              > O quanto cada uma das instância recebe de salário nesta pesquisa

"""

dados = pd.read_csv("Salary Data.csv")
dados.head(5)

dados.dtypes

dados.info()

"""Limpeza dos dados

"""

# verificando os valores ausentes no DF

dados.isnull().sum()

# existem dois registros com valores ausentes em todos as variáveis, devo analisar esses registros
# para tomar uma decisão sobre o que fazer com eles.

# colocar dentro de uma variável os registros que estão completamente vazios

ausentes = dados[dados.isnull().all(axis=1)]
ausentes

# fazendo uma análisa estastística simples, para vermos os impactos destes registros

dados.describe()

# a média dos valores registrado na coluna Age é bem próximo ao valor mediano da mesma, sendo a média = 37.431635	e a mediana = 36.000,
# esse padrão é igual as outras colunas de valores numericos como Years of Experience como média = 10.030831 e mediana = 9.000000 e
# Salary média = 100577.345 e mediana = 95000.000000

# devo alinhar esses valores com as colunas categóricas Gender, Education Level e Job Title.

G_unicos = dados['Gender'].unique()
G_unicos

contagem_valoresG= dados['Gender'].value_counts()
contagem_valoresG

E_unicos = dados['Education Level'].unique()

contagem_valoresE= dados['Education Level'].value_counts()
contagem_valoresE

cantagem_valoresT = dados['Job Title'].value_counts()
cantagem_valoresT

# Para substituir os valores ausentes por valores médios, vou me basear sobre as médias dos valores numéricos 
# sobre os dois valores ausentes, serão acrecentados 
# em -> Gender  'Male' e um 'Female'
# no campo Education Level, a grande maioria e de Bachelor's então decidi por os valores ausentes dentro dessa instância
# devo verificara a média salarial dos indivíduos para cada uma das variáveis categóticas.

media_salario_por_educacao = dados.groupby('Education Level')['Salary'].mean()
media_salario_por_educacao

media_salario_por_idade = dados.groupby('Age')['Salary'].mean()
media_salario_por_idade

media_salario_por_ano_experiencia = dados.groupby('Years of Experience')['Salary'].mean()
media_salario_por_ano_experiencia

media_salario_por_genero = dados.groupby('Gender')['Salary'].mean()
media_salario_por_genero

x = np.linspace(0, 2*np.pi, 400)
y = np.cos(10*x)
z = np.sin(10*x)


fig = plt.figure()
ax = plt.axes(projection='3d')
ax.plot3D(x, y, z)

ax.set_title("Primeiro Gráfico de um Coseno")
ax.set_xlabel("Os 200 pontos no intervalo de tempo de '0 até 6'")
ax.set_ylabel("Distribuição Normal")
ax.set_zlabel("lado oposto y")
plt.show()

sns.pairplot(dados, kind="reg")